### ISSUE TITLE
Tokenization mismatch

### ISSUE THREAD

**Issue by weiyuan-c** [huangb23/VTimeLLM#10]
![error](https://github.com/huangb23/VTimeLLM/assets/87663784/ab6e47b0-9a7f-42a6-b48e-d45470af0a5f)
Thank you for releasing the code. I have followed the instructions in the README file and downloaded the provided files, organizing them as suggested. However, I encountered some issues and have been unable to pinpoint the exact cause. Did you experience any similar bugs during implementation? I would greatly appreciate it if you could suggest any potential solutions or troubleshooting steps.

**Comment by huangb23** [comment]
Sorry, I haven't encountered the same issue during my implementation process. You can try using short sentences as data and observe the tokenization process for debugging.

**Comment by weiyuan-c** [comment]
I resolved this issue by switching the version of the data preprocessing from v1 to llama_2. I plan to spend some time understanding the differences between these two functions. Thank you for your response!

**Comment by itruonghai** [comment]
I encountered the same issue. How did you resolve it? What is the possible solution?

**Comment by weiyuan-c** [comment]
> I encountered the same issue. How did you resolve it? What is the possible solution?

I would like to share my observations here, though I cannot assert with certainty that this is the absolute reason. The potential explanation might be linked to tokenization. For example, the encoding result for 'USER' could change when it is preceded by another special token, like "\<s>USER".

![416462109_1045760906699032_5604932118681662578_n](https://github.com/huangb23/VTimeLLM/assets/87663784/4959c6a9-bcf8-4ae6-a05c-24f2cae4e01d)

**Comment by itruonghai** [comment]
Can you please check the released code again @huangb23 ?

**Comment by huangb23** [comment]
@itruonghai @weiyuan-c  I have been able to identify the root cause of this issue, which seems to be related to the updates in the Transformers library. As a temporary solution, you can address this problem by downgrading the Transformers library to an earlier version (4.31.0) using the following command: `pip install transformers==4.31.0`
