### ISSUE TITLE
Main differences between VTimeLLM and LLaVA

### ISSUE THREAD

**Issue by itruonghai** [huangb23/VTimeLLM#13]
Hi @huangb23, 

Thank you for your wonderful work. I would like to ask about the main differences between VTimeLLM and LLaVA. From my understanding, the main differences are Fine-tuning data (with moment retrieval format), and an additional fine-tuning with LoRA in stage 3. Is it correct?

Best

**Comment by huangb23** [comment]
Yes. our codebase is based on modifications to LLaVA. The primary distinctions include the fine-tuning data and an additional fine-tuning step in stage 3. Additionally, there is a difference in input representation.

In the case of LLaVA, it operates on a single image input, utilizing all patch features from CLIP as input. On the other hand, VTimeLLM processes 100 images as input and, as a result, employs only the CLS feature from each image as input.
