### ISSUE TITLE
can I simply query the model to locate the `highlight moment or the best moment` in the video?

### ISSUE THREAD

**Issue by dragen1860** [huangb23/VTimeLLM#17]
HI, Dear author:
  thanks for publishing such an insightful work. After reading your paper, i realise the training overload is really small, single GPU will be able to reproduce your work, which is really neat.  
  I would like to use your model to detect the highlight moment on my own video. I wonder how does it perform? thank you.

**Comment by huangb23** [comment]
I haven't attempted to perform a highlight detection task with this model before. Perhaps you might need to fine-tune it using similar data processing methods. Of course, you could also try directly performing it in a zero-shot manner. Feel free to share your results!

**Comment by dragen1860** [comment]
> I haven't attempted to perform a highlight detection task with this model before. Perhaps you might need to fine-tune it using similar data processing methods. Of course, you could also try directly performing it in a zero-shot manner. Feel free to share your results!

HI, I try your model on my own videos. To be honest, somethiems the timestamp is right but the description is not precise; sometimes the description is correct but the timestamp is far away from groudtruth. A big margin exists between the open source and Gemini 1.5.
 Anyway, you still made a good job, thank you.
