### ISSUE TITLE
Training Warning

### ISSUE THREAD

**Issue by Tanveer81** [huangb23/VTimeLLM#20]
Are these warnings expected? I get it at the end of both stage 2 and 3 training.

`WARNING:root:base_model.model.model.layers.31.mlp.down_proj.lora_B.default.weight: param.ds_status != ZeroParamStatus.NOT_AVAILABLE: ZeroParamStatus.NOT_AVAILABLE`

`/root/envs/vtimellm/lib/python3.10/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in /root/.cache/huggingface/hub/models--lmsys--vicuna-7b-v1.5/snapshots/de56c35b1763eaae20f4d60efd64af0a9091ebe5 - will assume that the vocabulary was not modified.`

**Comment by huangb23** [comment]
I've encountered similar warnings as well, but they don't seem to have caused any significant issues. Feel free to share if you've found a solution.
