### ISSUE TITLE
Linking id to DiDeMo video path

### ISSUE THREAD

**Issue by ZhangYuanhan-AI** [huangb23/VTimeLLM#21]
Hi team! 

Thanks for this great work!

One question:  In the stage3.json, how to find the DiDeMo video path using the "id"?

The videos in the DiDeMo:
<img width="778" alt="image" src="https://github.com/huangb23/VTimeLLM/assets/18485270/6a089d17-e90d-45b9-a9f3-5699dd4f90e8">

**Comment by huangb23** [comment]
```
id_before_hash = video_name.split('_')[1]
id = yfcc100m_hash[id_before_hash]
```
The `yfcc100m_hash` can be obtained from https://github.com/LisaAnne/LocalizingMoments/blob/master/data/yfcc100m_hash.txt. For example, in the first case shown in the figure, the `id_before_hash` is `2694756328`, and after hashing, the `id` becomes `4ed8934c6a45e01d59133159eccfaa8c`.

**Comment by sx1999** [comment]
> Hi team!
> 
> Thanks for this great work!
> 
> One question: In the stage3.json, how to find the DiDeMo video path using the "id"?
> 
> The videos in the DiDeMo: <img alt="image" width="778" src="https://private-user-images.githubusercontent.com/18485270/319079452-6a089d17-e90d-45b9-a9f3-5699dd4f90e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDk2MjEsIm5iZiI6MTcxMzI0OTMyMSwicGF0aCI6Ii8xODQ4NTI3MC8zMTkwNzk0NTItNmEwODlkMTctZTkwZC00NWI5LWE5ZjMtNTY5OWRkNGY5MGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA2MzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYjc1ZmRjZjlmNjNmODkyN2RmNjEwMDlhODM0MjRmYzMwYjIxYjg3NjkzOTc3MzdjYmRjZWRlMTE3Yzg5NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1jRh__FPYx37DYwAWlTMWcF6D_VcTWEYHhU_94qmcl4">

hi, could you share with me the DiDeMo dataset download link? thank you very much!

**Comment by huangb23** [comment]
> hi, could you share with me the DiDeMo dataset download link? thank you very much!

@sx1999 

https://drive.google.com/drive/u/0/folders/1_oyJ5rQiZboipbMl6tkhY8v0s9zDkvJc
