### ISSUE TITLE
NVIDIA Driver error - could not parse ModelProto

### ISSUE THREAD

**Issue by simran0112** [huangb23/VTimeLLM#24]
I am getting this error while running the inference code
![image (4)](https://github.com/huangb23/VTimeLLM/assets/25058826/add29487-c8c6-4d34-90f4-13e5fecbcb8d)

**Comment by huangb23** [comment]
It seems unrelated to our code. Maybe you should check whether your CUDA version matches the torch version you're using.

**Comment by simran0112** [comment]
my CUDA and torch version seem compatible (CUDA version is 11.8 and torch version is 2.2.2). what CUDA and torch versions did you use @huangb23 ?

thanks!!
