### ISSUE TITLE
How much time does it take to extract features in stage 2 and what is the hardware used?

### ISSUE THREAD

**Issue by Maulog** [huangb23/VTimeLLM#25]
Thank you for your excellent work!
 I was interested in the cost of extracting features from InternVid in stage 2 of your work. I would like to use other visual encoders to extract features for the dataset. Because I'm limited by the hardware, I have to think about this part of the cost. 
I would appreciate it for your answer.

**Comment by Maulog** [comment]
Addtionally, I would like to know the size of the 134k dataset, thank you!

**Comment by huangb23** [comment]
I'm afraid I don't remember the exact time it took as it has been some time since we conducted those experiments. However, , it should be possible to complete the feature extraction process using a single 3090 GPU in one or two days.

**Comment by huangb23** [comment]
The stage2 dataset includes approximately 134,000 videos, each with a corresponding QA pair. The videos were downloaded from YouTube at a resolution of around 360p. The original videos took up around 700GB of storage space.

**Comment by Maulog** [comment]
Many thanks for your replying.
