### ISSUE TITLE
Feature extraction code requirement

### ISSUE THREAD

**Issue by L4zyy** [huangb23/VTimeLLM#30]
Thank you for sharing this great work!

I am trying to train VTimeLLM model on my own small dataset through all three stages, but I cannot find any script or code about the feat extraction prerocess. I wonder if you can kindly share some code or scirpt to extract the image feat?

**Comment by huangb23** [comment]
You can find the relevant code for feature extraction in [vtimellm/inference.py](https://github.com/huangb23/VTimeLLM/blob/main/vtimellm/inference.py#L100). You can consider adding multi-processing or multi-GPU inference for acceleration based on your requirements.
