### ISSUE TITLE
stage2 features

### ISSUE THREAD

**Issue by simplewhite9** [huangb23/VTimeLLM#31]
Hello,
Thank you for your interesting work!
Just one thing, I was trying to unzip your stage2 features (part_aa and part_ab), and it seemed like part ab is corrupted.
part aa unzipped fine, but part ab would not work. 

Could there be any issues with it?

**Comment by huangb23** [comment]
you should follow our instructions in train.md:

```
cat stage2_part_* > stage2.tar.gz
tar -xzvf stage2.tar.gz
```

**Comment by simplewhite9** [comment]
Thankyou!

**Comment by simplewhite9** [comment]
Thank you!
