### ISSUE TITLE
Code to generate Stage 3 dataset from ActivityNet or DiDeMo

### ISSUE THREAD

**Issue by anilbatra2185** [huangb23/VTimeLLM#32]
Hi @huangb23,

Thanks for sharing code for a great work!

Can you please share the inference code to generate the Stage 3 Dataset from ActivityNet/DiDeMo? Specifically, the inference configuration for model to generate the response. I tried the following, however, the responses are different from the shared Stage3 data.

`tokenizer = AutoTokenizer.from_pretrained("checkpoints/vicuna-7b-v1.5/")`
`model = AutoModelForCausalLM.from_pretrained("checkpoints/vicuna-7b-v1.5/")`

<img width="636" alt="image" src="https://github.com/huangb23/VTimeLLM/assets/7984207/dfcf460b-fa4f-4290-a49b-da8d089f3392">

**Input Prompt**
![image](https://github.com/huangb23/VTimeLLM/assets/7984207/a0b72b0a-f259-4703-bf2b-14570737cd85)

**ActivityNet VideoID** - v_QOlSCBRmfWY

**Output in Shared Stage3 Json**

> User: What was the primary purpose of the video?
> Assistant: The primary purpose of the video appears to be showcasing the young woman's dance routine, highlighting her movements and expression while executing them.
> User: Can you pinpoint when the girl changes her pose or dance style?
> Assistant: From <s1> to <e1>, the girl transitions from one pose or dance style to another as the camera captures her movements.
> User: Is there any specific reason for the change in dance style or pose?
> Assistant: Based on the video content, there is no evident reason for the change in dance style or pose. It could be a creative decision by the videographer or an expression of the dancer's artistic expression.

**Generated Output**

> User: What is the primary action in the video?
> Assistant: The primary action in the video is the young woman’s dance, which spans from <s1>to <e1>.
> User: Can you pinpoint when she starts dancing?
> Assistant: The dancing commences from <s1>to <e1>.
> User: What is the woman’s expression during her dance?
> Assistant: I’m unable to provide an answer as the video doesn’t contain any explicit expressions. However, the woman’s movements can be observed to gain insights into her emotions.

**Comment by huangb23** [comment]
When generating the dataset, we found that the data generation results from Vicuna-7B were not always consistent. Therefore, we generated multiple responses for each data point and applied some simple filtering rules (e.g., checking if the timestamps match the events, the number of conversation turns, etc.) to select the final responses.

You can try some better LLM such as GPT-4 or LLaMA3 ~

**Comment by jiyi-zyh** [comment]
Excuse me, do you have the code for generating the training features for stage 2 and stage 3? I tried to extract the features from the original video using the encoding method in inference.py, and found that the results do not match the features of the training set provided by the author.
