### ISSUE TITLE
About training.

### ISSUE THREAD

**Issue by EdenGabriel** [huangb23/VTimeLLM#34]
Thank you for your excellent work!

For training of stage 1, should I set the DEFAULT_IMAGE_TOKEN in constants.py to `<image>`? The reason I have this question is because I saw in Section 3.2.1 of your paper that you said ‘a special token `<image>` is directly appended before the text T’.

Furthermore, There is a description about 'the embedding of this token is extracted with the visual encoder and the visual adapter'. But when i debug the demo, this special token is not fed into the visual encoder, just is fed into the visual adapter. 

Looking forward to your reply. Thanks.

**Comment by congwei45** [comment]
I have the same problem.

**Comment by huangb23** [comment]
@congwei45 @EdenGabriel  The visual encoder is the ViT from CLIP. I extracted the features in advance before training, so they are not included in the training code. However, you can see the full process in inference.py.

**Comment by congwei45** [comment]
I saw in Section 3.2.1 of your paper that you said ‘a special token <image> is
directly appended before the text T’. But in the code you put <video> in
the text T.

huangb23 ***@***.***> 于2024年10月25日周五 15:35写道：
