### ISSUE TITLE
InternVID training dataset

### ISSUE THREAD

**Issue by LengSicong** [huangb23/VTimeLLM#4]
May I know if you can provide a download link for the InterVID videos?

**Comment by huangb23** [comment]
The InternVID videos are sourced from YouTube, and in compliance with YouTube's policies, we are unable to directly provide the original video files. However, you can to download them using tools like youtube-dlp by utilizing the specific YouTube ID associated with the video.

**Comment by LengSicong** [comment]
Hi Dr.Huang, I have sent a private email to you. May I bother you to take a look at it for further discussion?
