### ISSUE TITLE
Regarding the Second Phase of Training for the VTimeLLM Model

### ISSUE THREAD

**Issue by jiyi-zyh** [huangb23/VTimeLLM#41]
Very meaningful work!
I would like to inquire about the process of generating features for the second stage of training. I downloaded the InternVid-10M-FLT dataset, as mentioned in your paper, from OpenDataLab (link: https://opendatalab.org.cn/vd-foundation/InternVid-10M-FLT), and I intend to extract features myself. However, I noticed that in the stage2.json file, each video ID corresponds to more than one original video from the InternVid-10M-FLT dataset files I downloaded (for a detailed example, refer to figures bellow, where the original video with the ID 3n3oCNerzV0 has three segmented original videos in the dataset I downloaded). This has left me unsure of how to extract the features. I would like to ask if there is a mistake in my steps or if you would be willing to share the original videos and code for extracting features in the second and third stage.  Thank you very much for your response!
![微信图片_20241021234116](https://github.com/user-attachments/assets/16278730-9bbf-4208-87bc-dd8ef7b7dcdd)
![微信图片_20241021234127](https://github.com/user-attachments/assets/5ac21c3c-72fb-40dd-ad97-7d6bdaa892f4)

**Comment by huangb23** [comment]
It seems you won't be able to use the data downloaded from OpenDataLab, but instead, you need to download the original videos from YouTube (consider using tools like yt-dlp). For example, the link to the video you provided is https://www.youtube.com/watch?v=3n3oCNerzV0, and you should extract the relevant video segment according to js['meta']['split'] (e.g., in this case, from 129.8s to 184.0s, which is from 02:09 to 03:04), then proceed with feature extraction.

Here’s a more detailed explanation: InternVid segments multiple short clips from a single YouTube video, each labeled separately. However, these individual clip-caption data are not suitable for tasks like dense captioning, which require multiple segments. What we do is find a long segment that contains several short segments, thereby creating a dataset with multiple segment annotations. (For instance, as shown in Figure 2, the segment we cropped contains two segment annotations, located at 02:09–02:19 and 02:59–03:04 of the original video.)
